Task #18
bmstu-iu9/ptp2022-10-2d-game pull request #22
Opened 2022-11-02 09:36 UTC by egorkacc

Added the possibility to access debug mode panel through pause menu. The access is granted by clicking on the blue button with letter "D". Arranged prospects for further cheats additing. Added new hotkeys to be able to move with "AWSD", "LeftUpDownRight" and "Space". Reworked the Neuton force mechanics a little bit and added some new temporary constants. Removed final marks from some variables such as GRAVITY, for instance, to be able to implement cheats to the game.

2022-11-02 11:52 UTC, Mazdaywik requested changes
Содержательно посмотрю потом, формальные изменения нужно внести.

2022-11-02 11:52 UTC, Mazdaywik commented on README.md
> +jump: ```W```
Зачем откатили правку в `README.md`?

2022-11-02 11:52 UTC, Mazdaywik commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
Зачем закоммитили файлы в папке `.idea`? Удаляйте их.

2022-11-07 11:39 UTC, egorkacc commented on README.md
> +jump: ```W```
Добавил классическую возможность прыжка на клавишу W.

2022-11-07 14:10 UTC, Mazdaywik approved these changes
Одобряю!

2022-11-07 14:14 UTC, Mazdaywik requested changes
Слейте, пожалуйста, четыре предшествующих коммита в один:
```
git rebase -i 56cf42
```

В открывшемся текстовом редакторе напишите:
```
pick 1be234a .idea del
squash 4d6e209 .idea del
squash 6c49389 .idea del
squash f049dac .idea del
```

Снова откроется текстовый редактор, в нём сотрите всё и введите
```
Удалены случайно сохранённые файлы
```

2022-11-07 15:00 UTC, egorkacc commented
22 готов, Александр Владимирович.

2022-11-07 15:12 UTC, Mazdaywik approved these changes
Вот теперь здорово!

2022-11-07 15:12 UTC, merged